apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: weather
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  selector:
    matchLabels:
      app: weather
  replicas: 2
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: devops45of/app:5b05c625679e58fcea13f03d45c663e4c2ac9c69
        env:
          - name: BG_COLOR
            value: 'green'


