name: argocd 

on:
  workflow_run:
    workflows: ["dev pipeline"]
    types:
      - completed

jobs:
  argocd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Change image tag in deployment
        run: |
          # Update the deployment YAML with the new image tag
          sed -i 's|image: devops45of/app:.*|image: devops45of/app:${{ github.event.workflow_run.head_commit.id }}|g' deploy/deployment.yml
      
      - name: Commit changes
        run: |
          git add deploy/deployment.yml
          git commit -m "Update image tag to ${{ github.event.workflow_run.head_commit.id }}"
          git push origin main 
